#!/bin/sh

mvn compile package install assembly:single
java -jar lib/Rootbeer-1.2.3.jar target/matrix-rbbasic-1.0.0-jar-with-dependencies.jar matrix-rbbasic-gpu-1.0.0.jar -noexceptions -noarraychecks -64bit
