#!/bin/sh

mvn compile package install assembly:single
java -jar lib/Rootbeer.jar target/matrix-rbshared-1.0.0-jar-with-dependencies.jar matrix-rbshared-gpu-1.0.0.jar -64bit -shared-mem-size 16384 -maxregcount 32
